### ISSUE TITLE
Feat: Faster Install and Usage via .exe and .deb

### ISSUE THREAD

**Issue by vednig** [BolisettySujith/J.A.R.V.I.S#15]
### **Is your feature request related to a problem? Please describe.**
Every user that wants to use Cortona or Google Assistant or Alexa (top 3 AI projects today) doesn't need to go through the painful process of building it for themselves instead they should be able to install and try it in one click.

### **Describe the solution you'd like**
One way is to create .exe files and release them with release section on github. 

### **Describe alternatives you've considered**
An alternative to try out J.A.R.V.I.S can be to use Brython and run it in the browser.

**Comment by BolisettySujith** [comment]
@vednig thanks for suggesting a feature.

Actually, there is another way for creating a *.exe*, i.e using [pyinstaller](https://pypi.org/project/pyinstaller/). 

It can be included by creating a CI/CD to this repository or anyone can take this source code and if anyone wants to change anything in the code they can do it and run the pyinstaller command in their local system.

If you are interested in this repository you can make a PR for CI/CD script that will create a *.exe* file.

Thank you.
