### ISSUE TITLE
misleading feature - phone tracking

### ISSUE THREAD

**Issue by freyfogle** [BolisettySujith/J.A.R.V.I.S#17]
Ed from OpenCage here.

OpenCage can not be used to determine the location of a phone just based on phone number.
Please see [our blog post about this](https://blog.opencagedata.com/post/we-can-not-convert-a-phone-number-into-a-location-sorry).

Please can you clarify this in the README (happy to submit a pull request if you like)?
Many people believe this service can track a phone just based on number, which is just not true.

**Comment by BolisettySujith** [comment]
Hi @freyfogle 

I initially thought this library used to track the phone numbers and get the geo-coordinates and got to know about this from a YT source, but yeah actually now after seeing that blog I too realized that how can a library determine exact position of a phone number without having any permissions.

You are welcome to submit a pull request.


Thank you :)
