### ISSUE TITLE
how can i remove the gui?

### ISSUE THREAD

**Issue by San5157** [BolisettySujith/J.A.R.V.I.S#22]
**Describe the bug**

**To Reproduce**

**Current behavior**
A clear and concise description of what issues the bug causing.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by BolisettySujith** [comment]
In the recent updates, I have added this you can check this out at [JarvisWithoutGUI.py](https://github.com/BolisettySujith/J.A.R.V.I.S/blob/main/JarvisWithoutGUI.py)


Just run: `python JarvisWithoutGUI.py`

It will start the terminal version of Jarvis

**Comment by BolisettySujith** [comment]
I'm closing this issue, feel free to reopen it if you have any doubts.
